---
title: 'OMCA - Homework 2 - Regression: Satisfaction'
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the data

```{r}
## Basic setup ##
rm(list = ls())


## Load Data ##
data <- read.csv("https://raw.githubusercontent.com/Damanpreet7/Regression-Satisfaction/main/OMCA_Homework_Regression-Satisfaction_Data%20(1).csv", header=TRUE, row.names = 1, sep=",")

## Make Location a Factor
data$Location <- factor(data$Location, 
                        levels = c(0,1),
                        labels = c("City", "Suburb"))
```


## Does Delivery Speed improve Satisfaction?

```{r}
library(ggplot2)
ggplot(data, aes(x=Delivery.Speed, y=Satisfaction)) + 
  geom_point() +
  geom_smooth(method=lm) +
  theme_light() +
  ggtitle("Satisfaction and Delivery Speed") +
  theme(plot.title = element_text(hjust = 0.5))

m1 <- lm(Satisfaction ~ Delivery.Speed, data)
summary(m1)
```

## What about the other variables?

```{r}
m2 <- lm(Satisfaction ~ ., data[2:11])
summary(m2)

m3 <- lm(Satisfaction ~ ., data[2:12])
summary(m3)

m5 <- lm(Satisfaction ~ Delivery.Speed + Quality.percption + E.Commerce.experience + Complaint.resolution + Location, data[2:12])
summary(m5)
```

## What about the interaction of Delivey Speed and Location?

```{r}
ggplot(data, aes(x=Delivery.Speed, y=Satisfaction, color=Location)) + 
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  theme_light() +
  ggtitle("Satisfaction and Delivery Speed") +
  theme(plot.title = element_text(hjust = 0.5))


m4 <- lm(Satisfaction ~ . + Location*Delivery.Speed, data[2:12])
summary(m4)
```


#### Let's compare the results using Texreg (Alternative: Stargazer)
```{r}
library(texreg)

screenreg(list(m1, 
               m2,
               m3,
               m4),
          caption="Drivers of Satisfaction",
          dcolumn=FALSE,
          digits=2,
          leading.zero = FALSE,
          custom.model.names=c("M1", "M2", "M3", "M4"), 
          custom.header = list("No interaction" = 1:3, "Interaction" = 4), 
          reorder.coef = c(2:12, 1))
```
